version: '3'

tasks:
  up:
    desc: Run MinIO in Docker
    cmds:
      - mkdir -p ./data
      - |
        docker run -d --rm \
          --name minio \
          -p 9000:9000 \
          -p 9001:9001 \
          -e MINIO_ROOT_USER=admin \
          -e MINIO_ROOT_PASSWORD=admin123 \
          -v ./data:/data \
          minio/minio:latest server /data --console-address ":9001"

  down:
    desc: Stop MinIO container
    cmds:
      - docker stop minio || true

  cli:
    desc: Run MinIO Client (mc) command via wrapper
    cmds:
      - ./mc.sh {{.CLI_ARGS}}
    silent: true
